# Generated by Django 4.2.1 on 2023-05-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mehsullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Mehsul adi')),
                ('cost', models.IntegerField(verbose_name='Qiymet')),
                ('desc', models.CharField(max_length=100, verbose_name='Mehsul haqqinda')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='', verbose_name='Sekil')),
            ],
        ),
    ]
